// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBanco.API.Data;

#nullable disable

namespace ProjetoBanco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510100100_cp5")]
    partial class cp5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.API.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.ToTable("AGENCIAS");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCIA_ID");

                    b.Property<string>("DISCRIMINATOR")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("DISCRIMINATOR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("CLIENTES", t =>
                        {
                            t.Property("DISCRIMINATOR")
                                .HasColumnName("DISCRIMINATOR1");
                        });

                    b.HasDiscriminator<string>("DISCRIMINATOR").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PROCESSAMENTO");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SOLICITACAO");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MOTIVO_RECUSA");

                    b.Property<string>("NumeroGrupo")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NUMERO_GRUPO");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARCELA_ATUAL");

                    b.Property<decimal?>("ParcelaMensal")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PARCELA_MENSAL");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<decimal?>("SaldoRestante")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SALDO_RESTANTE");

                    b.Property<int?>("ScoreCredito")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_CREDITO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_PAGO");

                    b.Property<decimal?>("ValorTotalComJuros")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_TOTAL_COM_JUROS");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CONTRATACOES");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("PRODUTO_TIPO")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.Property<string>("ProdutoTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PRODUTO_TIPO");

                    b.HasKey("Id");

                    b.ToTable("PRODUTOS", t =>
                        {
                            t.Property("PRODUTO_TIPO")
                                .HasColumnName("PRODUTO_TIPO1");
                        });

                    b.HasDiscriminator<string>("PRODUTO_TIPO").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"CPF\" IS NOT NULL");

                    b.ToTable("CLIENTES", t =>
                        {
                            t.Property("DISCRIMINATOR")
                                .HasColumnName("DISCRIMINATOR1");
                        });

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"CNPJ\" IS NOT NULL");

                    b.ToTable("CLIENTES", t =>
                        {
                            t.Property("DISCRIMINATOR")
                                .HasColumnName("DISCRIMINATOR1");
                        });

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Consorcio", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Produto");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<decimal>("TaxaAdministracao")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAXA_ADMINISTRACAO");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_PARCELAS");

                    b.Property<decimal>("ValorBem")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_BEM");

                    b.ToTable("PRODUTOS", t =>
                        {
                            t.Property("PRODUTO_TIPO")
                                .HasColumnName("PRODUTO_TIPO1");
                        });

                    b.HasDiscriminator().HasValue("CONSORCIO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Consórcio para aquisição de imóvel residencial",
                            Nome = "Consórcio Imóvel",
                            ProdutoTipo = "CONSORCIO",
                            Categoria = "IMOVEL",
                            TaxaAdministracao = 1.2m,
                            TotalParcelas = 200,
                            ValorBem = 300000m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Consórcio para aquisição de veículo",
                            Nome = "Consórcio Veículo",
                            ProdutoTipo = "CONSORCIO",
                            Categoria = "VEICULO",
                            TaxaAdministracao = 1.5m,
                            TotalParcelas = 60,
                            ValorBem = 80000m
                        });
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Emprestimo", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Produto");

                    b.Property<int>("Parcelas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARCELAS");

                    b.Property<int>("ScoreMinimo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_MINIMO");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAXA_JUROS");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_SOLICITADO");

                    b.ToTable("PRODUTOS", t =>
                        {
                            t.Property("PRODUTO_TIPO")
                                .HasColumnName("PRODUTO_TIPO1");
                        });

                    b.HasDiscriminator().HasValue("EMPRESTIMO");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Descricao = "Empréstimo pessoal com análise de score de crédito",
                            Nome = "Empréstimo Pessoal",
                            ProdutoTipo = "EMPRESTIMO",
                            Parcelas = 24,
                            ScoreMinimo = 600,
                            TaxaJuros = 2.5m,
                            ValorSolicitado = 10000m
                        });
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Cliente", b =>
                {
                    b.HasOne("ProjetoBanco.API.Models.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Contratacao", b =>
                {
                    b.HasOne("ProjetoBanco.API.Models.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoBanco.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
